version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
    - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore NLog.Ifttt.sln --verbosity m
build_script:
  - cmd: dotnet publish NLog.Ifttt.sln -o artifacts --verbosity m --framework netstandard1.3 --runtime any
after_build:
  - cmd: dotnet pack src/NLog.Ifttt/NLog.Ifttt.csproj --output ../../nupkgs
artifacts:
  - path: artifacts
    name: bin
    type: zip
    
  - path: 'nupkgs\*.nupkg'
    name: nupkgs
clone_depth: 1
test_script:
on_finish:
deploy:
  provider: NuGet
  api_key:
    secure: 9wj2UdhWXMnspugsKG2d35NGV6AqGUJUPrdafkEljDvyFk1b0cNm3EK+MDhEBnxb
  artifact: nupkgs/*.nupkg